### ISSUE TITLE
Different Inputs/Output

### ISSUE THREAD

**Issue by ChristianKniep** [graphite-ng/carbon-relay-ng#103]
Hey Dieter,
love your `carbon-relay-ng` approach. I would love it even more if I could use it as a normalizer of 
multiple metric producers and relay in front of different metrics consumers.

Internally you use a tuple for data processing. What do you reckon should be an approach to hack in the direction I disribed? Use the most flexible structure within `carbon-relay-ng` - like OpenTSDB or Influxdb?

I assume I could hack the InfluxDB line input into carbon-relay and flaten out the tags, but it would be nicer to handle the tags internaly. This could also allow a real Metrics2.0 input that forwards to different back-ends. :)

**Comment by Dieterbe** [comment]
i'm torn about this. obviously i love the idea of more structure, tags and metrics2.0 support,
OTOH implementing a more structured type introduces complexity and overhead, but maybe not so much that i should worry about it. i guess we could have metrics as structs with a `map[string]string` for tags, or something like that. or a `[]string`. the latter lets us encode tags that don't have keys, (and for tags with keys we'd do `foo=bar` strings. but it gets messier if you want to support equals signs in the tag key/values, but i don't think that would be an issue.

**Comment by Dieterbe** [comment]
actually hold on a second. you know, the in my opinion, major issue with the graphite TCP proto approach, is that if your graphite endpoint goes down, you have no way to know which metrics it was able to successfully process, so carbon-relay-ng is engineered around that to just resend the last (i forgot.. 1000 or so?) metrics when it comes back up and that should hopefully do it.
if you're using opentsdb/influxdb, those systems hopefully provide you with acknowledgments upon successfull ingestion of data (as does graphite's amqp btw). and in such case it makes sense to leverage acks throughout the system, which is (like tags/structure) such a major difference in implementation.

so maybe, if you want to use influxdb/opentsdb it would be better to look at something like NSQ (simple to setup, order not guaranteed, requires separate programs for input and ingest) or kafka (order guaranteed but complex to setup, requires separate programs for input and ingest) or heka (simple to setup, order guaranteed (i think), and has various input/output plugins, but is single-node). actually heka is probably the best fit. with either of these 3 you can structure your messages however you like, heka also has built in aggregators I think and comes pretty close in terms of processing that's supported out of the box.

**Comment by ChristianKniep** [comment]
Hey Dieter, I deal with kafka at work (at least I got my feet wet) but I want something nice and simple.
I tipped my toe into heka the last couple of month and it might be doable to have a on-demand relay by using some lua-andbox plugins. I was thinking that an extention of your project would be nicest, since it got a clear focus, a simple UI and an on demand relay.
But your are right, maybe getting into heka a bit more could help form an implementation into carbon-relay-ng. :)
I will kepp that in mind for a couple of days and see how I can incorperate that thought. Have to provide a relaying piece at work...

**Comment by ChristianKniep** [comment]
I'll close the issue until I got an aproach. Thx

**Comment by Dieterbe** [comment]
good luck :) i know it's not easy, i've been struggling with this as well (with no decision or tangible outcome)

**Comment by KlavsKlavsen** [comment]
I can understand there's now kafka support and metrics 2.0.. any "official best way" - to use this to forward to f.ex. both graphite and influxdb installation? (I use influxdb graphite port today - but grafana cannot handle 300 servers (with many counters per server) - when data is readin via influxdb graphite port)

**Comment by Dieterbe** [comment]
Doesn't sound like a grafana problem. Any performance issues encountered from grafana are typically problems in the datastore or the specific query used. Beyond treating influx as yet another carbon port , the relay currently does not support influxdb. That said we're aiming now to work with more structured messages that can hold tags.

**Comment by KlavsKlavsen** [comment]
Problem is that when you read all in via influxdb graphite port - they end up in one tag - so grafana gets ALL counters in one read - which takes ~20 seconds to respond  - and thats appearently too many - so it does not work (its ~100k results in one read when you try to 'browse influxdb' via grafana. Looking forward to seeing structured messaging support.. could be nice to be able to send to other systems. Currently I'm thinking of letting it send to prometheus instead - since it has a daemon for that.
