### ISSUE TITLE
OpenTSBD

### ISSUE THREAD

**Issue by maxsolyaris** [graphite-ng/carbon-relay-ng#106]
Hey!

How I can you this stuff 
https://github.com/graphite-ng/carbon-relay-ng/blob/master/_third_party/github.com/Dieterbe/go-metrics/opentsdb_test.go
to route into opentsdb?

How is sholld work? How you match that this code behind route_key is OpenTSDB or Influx?
Thanks!

**Comment by Dieterbe** [comment]
Carbon-relay-ng does not support opentsdb at this point. You're a file of the instrumentation library it uses.

**Comment by maxsolyaris** [comment]
Thanks for answer Dieterbe. Would be nice to have this feature in future.
