### ISSUE TITLE
cant build carbon relay

### ISSUE THREAD

**Issue by rgardam** [graphite-ng/carbon-relay-ng#118]
I followed the documentation in the readme and I get the following error during make

./route_grafananet.go:116: unknown http.Transport field 'ExpectContinueTimeout' in struct literal

**Comment by Dieterbe** [comment]
it looks like this is a new field as of go 1.6, judging from https://golang.org/doc/go1.6
are you able to use go 1.6 ? what's your version ?

**Comment by rgardam** [comment]
Ah yes, quite an older version.

1.4.2-9.el7

I have used the v0.6 release and this has fixed the issue for the moment.

**Comment by Dieterbe** [comment]
@rgardam could you try applying this patch:

```
diff --git a/route_grafananet.go b/route_grafananet.go
index 7fc253a..955443a 100644
--- a/route_grafananet.go
+++ b/route_grafananet.go
@@ -112,9 +112,9 @@ func (route *RouteGrafanaNet) run() {
                                Timeout:   30 * time.Second,
                                KeepAlive: 30 * time.Second,
                        }).Dial,
-                       TLSHandshakeTimeout:   10 * time.Second,
-                       ExpectContinueTimeout: 1 * time.Second,
-                       // except for this
+                       TLSHandshakeTimeout: 10 * time.Second,
+                       // except we removed ExpectContinueTimeout cause it doesn't seem very useful, requires go 1.6, and prevents using http2.
+                       // and except for this:
                        TLSClientConfig: &tls.Config{
                                InsecureSkipVerify: true,
                        },
```

and see if you can build it (the latest git version with that patch) using your go 1.4.2 ?

**Comment by anatolijd** [comment]
Thanks Dieter, 
I have been facing the same error during make with golang-1.5.1.
Build completed successfully after the patch applied.

**Comment by rgardam** [comment]
I hadn't tried this yet for us.
I'm afraid I had to move onto something else. :)

**Comment by msaraf** [comment]
Just to provide additional confirmation; I ran into the same issue and the patch fixed the build.

**Comment by Dieterbe** [comment]
cool thanks for confirming, will commit the fix!
