### ISSUE TITLE
How to avoid regex usage

### ISSUE THREAD

**Issue by mrh666** [graphite-ng/carbon-relay-ng#121]
Hi there,

I have a metrics namespace statsite.(gauges|timers|counts).department and I want to define different routes per department. Is there is any way to avoid ```regex=^statsite\.(gauges|timers|counts)\.department\..*$``` and to use sub or prefix definition with * in one line? 

Something like ```addRoute sendAllMatch foo prefix=statsite.*.department  endpoint```?

Thank you

**Comment by mrh666** [comment]
@Dieterbe It works. But there is some bug I presume.
This is my ini file definition ( I'm using v0.7 binary - https://github.com/mrh666/carbon-relay-ng/releases compiled from v0.7 source code - https://github.com/graphite-ng/carbon-relay-ng/releases )
```
'addRoute sendAllMatch influx-dep-a prefix=statsite.gauges.dep-a  172.31.44.95:2012 spool=true pickle=false  172.31.45.212:2012 spool=true pickle=false',
'addRoute sendAllMatch influx-dep-b prefix=statsite.timers.dep-b  172.31.44.95:2012 spool=true pickle=false  172.31.45.212:2012 spool=true pickle=false',
```

Errors in /var/log/messages:

```
May 31 20:54:17 carbon-relay-ng-172 carbon-relay-ng: 2016/05/31 20:54:17 ERROR: diskqueue(spool_172_31_44_95_2012) failed to sync - rename /var/spool/carbon-relay-ng/spool_172_31_44_95_2012.diskqueue.meta.dat.tmp /var/spool/carbon-relay-ng/spool_172_31_44_95_2012.diskqueue.meta.dat: no such file or directory
May 31 20:54:17 carbon-relay-ng-172 carbon-relay-ng: 2016/05/31 20:54:17 ERROR: diskqueue(spool_172_31_45_212_2012) failed to sync - rename /var/spool/carbon-relay-ng/spool_172_31_45_212_2012.diskqueue.meta.dat.tmp /var/spool/carbon-relay-ng/spool_172_31_45_212_2012.diskqueue.meta.dat: no such file or directory
```

The content of /var/spool/carbon-relay-ng/ directory:

```
[root@carbon-relay-ng-172 ~]# ls -la /var/spool/carbon-relay-ng/
total 60
drwxr-xr-x. 2 root root 4096 May 31 20:58 .
drwxr-xr-x. 8 root root   88 May 29 09:36 ..
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_44_222_2004.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_44_95_2003.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_44_95_2011.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_44_95_2012.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_44_95_2013.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_44_95_2014.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_45_212_2003.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_45_212_2011.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_45_212_2012.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_45_212_2013.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_45_212_2014.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_172_31_45_86_2004.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_graphite_prod_2003.diskqueue.meta.dat
-rw-------. 1 root root   10 May 31 20:58 spool_graphite_staging_2003.diskqueue.meta.dat
```

Some lack of permissions or something? I even try to stop service, remove all the files from /var/spool/carbon-relay-ng/, start the service. But the errors still the same...

Any idea how to fix it of work it around?
Thank you!

**Comment by Dieterbe** [comment]
oh right. the problem is currently the spool names are generated from the destination addresses. if you use the same destination address multiple times, that will cause trouble.

that's a bug to be fixed.  as a quick workaround you can also disable spooling

**Comment by mrh666** [comment]
@Dieterbe Great news - more bugs discovered - more stability later )

Right, as soon as I set spool=false there is no more error messages. But will it seriously affects the performance?

**Comment by mrh666** [comment]
@Dieterbe Any news on spooling bugfix?

**Comment by Dieterbe** [comment]
No Sorry. See #64
