### ISSUE TITLE
metrics are dropped if have colon in the metric name

### ISSUE THREAD

**Issue by edieship** [graphite-ng/carbon-relay-ng#126]
I'm sending some metrics which have colon in the name to carbon relay, for some reason those metrics are dropped and no errors or anything found in the logs. It worked fine if removing the colon from the metric name.

So I'm guessing it's due to the special character ':', anyone know the reason?

By the way, I also tested by sending those metrics directly to graphite which worked well.

**Comment by edieship** [comment]
I overlooked this rule for the incoming metrics in the document:

* the key has no characters beside a-z A-Z _ - . = (fairly strict but graphite causes problems with various other characters)

so colon is not accepted for now. 

maybe should consider adding support for colon? since it is accepted by graphite.

**Comment by Dieterbe** [comment]
support for `:` is problematic in graphite. see https://github.com/graphite-project/graphite-web/issues/604 , it may look like it works, until you hit a function where it doesn't.

**Comment by Dieterbe** [comment]
.. and as such, i think the validation rule makes sense.  I would strongly advise you to stop using the colon key in your metrics (or get it fixed in graphite), in the meantime you can just disable validation.

**Comment by wjaspers** [comment]
just out of curiosity, why isn't there a validation against the metric name when data is fed in then?

I've seen this issue in other situations, and until 0.10.x having a colon in the metric path was rendering as expected.
