### ISSUE TITLE
What limits spooling?

### ISSUE THREAD

**Issue by tuomassalo** [graphite-ng/carbon-relay-ng#129]
I have carbon-relay-ng on a remote RPi server that has an unreliable internet connection with shorter and longer outages and occasional high latency. The `spool=true` seems to mostly work: sometimes the information for the last two hours is missing, and a bit later it is filled retroactively.

But sometimes the gaps are not filled. Is there a maximum size for the spool, maximum expiry time or something else that could cause this behaviour?

And yes, the data is constantly gathered and sent to carbon-relay-ng.

Here's an example of gaps:

![gaps](https://cloud.githubusercontent.com/assets/189964/17738391/be109074-6499-11e6-8da5-1ed5e44447d0.png)

**Comment by Dieterbe** [comment]
there's probably a few things i can think of.
but first of all, install the included dashboard (the json is in this repo or get it from https://grafana.net/dashboards/338 ), and check the "dest metrics drops". it'll drop metrics in a few cases
