### ISSUE TITLE
Relay to multple destinations

### ISSUE THREAD

**Issue by xymff** [graphite-ng/carbon-relay-ng#133]
Hello

I want to relay same the incoming data to multiple IPs. How would I go about doing this?

I currently have the following but does consistentHashing shard the data or duplicate it?
'addRoute consistentHashing carbon-default  xxx.xxx.xxx.5:2003  xxx.xxx.xxx.6:2003 spool=true pickle=false'

**Comment by pawellesniewski** [comment]
@xymff you can easily duplicate your incomming metrics by replacing consistentHashing with sendAllMatch function, like this:
```
 'addRoute sendAllMatch carbon-default  xxx.xxx.xxx.5:2003  xxx.xxx.xxx.6:2003 spool=true pickle=false'
```
Do not forget about double spaces between each destinations and after the route "name".

**Comment by Dieterbe** [comment]
>  does consistentHashing shard the data or duplicate it

it shards. anyway above comment answers the problem.
