### ISSUE TITLE
Losing pickle metric with multiples carbon-cache destinations

### ISSUE THREAD

**Issue by maauso** [graphite-ng/carbon-relay-ng#136]
Hi,

I'm trying to put graphite-ng on top to my graphite infrastructure, I will want to have one graphite-ng that It'd balancer to 3 carbon-cache (go-carbon) I have the below configuration 

```
instance = "default"

max_procs = "10"

listen_addr = "0.0.0.0:2004"
admin_addr = "0.0.0.0:8080"
http_addr = "0.0.0.0:8081"
spool_dir = "/var/spool/carbon-relay-ng"
#pid_file = "/var/run/carbon-relay-ng.pid"
#one of critical error warning notice info debug
log_level = "info"
# How long to keep track of invalid metrics seen
# Useful time units are "s", "m", "h"
bad_metrics_max_age = "24h"
# Metric name validation strictness for legacy metrics. Valid values are:
# strict - Block anything that can upset graphite: valid characters are [A-Za-z0-9_-.]; consecutive dots are not allowed
# medium - Valid characters are ASCII; no embedded NULLs
# none   - No validation is performed
validation_level_legacy = "none"
# Metric validation for carbon2.0 (metrics2.0) metrics.
# Metrics that contain = or _is_ are assumed carbon2.0.
# Valid values are:
# medium - checks for unit and mtype tag, presence of another tag, and constency (use = or _is_, not both)
# none   - No validation is performed
validation_level_m20 = "medium"

# you can also validate that each series has increasing timestamps
validate_order = false

# put init commands here, in the same format as you'd use for the telnet interface
# here's some examples:

init = [
     'addRoute sendAllMatch default  10.2.5.215:2004 spool=true pickle=true  10.2.10.201:2004 spool=true pickle=true  10.2.10.202:2004 spool=true pickle=true',
]

[instrumentation]
# in addition to serving internal metrics via expvar, you can optionally send em to graphite
graphite_addr = ""  # localhost:2003 (how about feeding back into the relay itself? :)
graphite_interval = 1000  # in ms
```

I'm sending pickel metrics and tcp metrics, unfortunately I am only receiving tcp metrics in carbons-cache, I did a tcpdump and the Pickel metrics arrive to graphite-ng, but not to carbon-cache. 

Some times only with one carbon-cache the carbon-relay works. 

If I send the metrics direcly to carbon-cache I don't have any problem. 

what could be the problem ?

**Comment by pawellesniewski** [comment]
@maauso carbon-relay-ng doesn't accept metrics in pickle protocol but it has support for sending them to receivers (pickle=false or pickle=true).

**Comment by maauso** [comment]
@pawellesniewski  With the configuration that I put in the first comment, we have the behavior that I commented, is it a normal behavior?

**Comment by pawellesniewski** [comment]
> Some times only with one carbon-cache the carbon-relay works. 
I think is it no possible because carbon-relay-ng don't support pickle protocol on ingest.

I guess it is related to cache in carbon-cache daemon, which can dump datapoints on disk on shutdown (refer to MAX_UPDATES_PER_SECOND_ON_SHUTDOWN carbon.conf variable). To check this, stop carbon-cache, rm whisper files from FS, start and check :)

**Comment by poblahblahblah** [comment]
FWIW it looks like carbon-relay-ng now supports receiving metrics in pickle protocol via https://github.com/graphite-ng/carbon-relay-ng/pull/140

**Comment by Dieterbe** [comment]
Closing. Feel free to reopen when you hit issues with the new version.
