### ISSUE TITLE
I've got this error

### ISSUE THREAD

**Issue by juaniterrarosa** [graphite-ng/carbon-relay-ng#138]
ERROR: for carbon  Cannot start service carbon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/bin/carbon-relay-ng\\\": permission denied\"\n"
ERROR: Encountered errors while bringing up the project.

Here you have the Dockerfile, I can't find the problem.

`FROM ubuntu:14.04

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:gophers/go
RUN add-apt-repository ppa:ubuntu-lxc/lxd-stable
RUN apt-get update
RUN apt install -y git make golang libreadline6 libreadline6-dev dialog

ENV VERSION master
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

RUN go version

RUN apt-get update 
RUN go get -d github.com/graphite-ng/carbon-relay-ng && \
    go get github.com/jteeuwen/go-bindata/... && \
    cd "$GOPATH/src/github.com/graphite-ng/carbon-relay-ng" && \
    git checkout $VERSION && \
    make

RUN mv /go/src/github.com/graphite-ng/carbon-relay-ng /bin/

VOLUME /conf

ENTRYPOINT ["/bin/carbon-relay-ng"]

RUN chmod 777 /bin/carbon-relay-ng
RUN chmod 777 /bin/carbon-relay-ng/examples/carbon-relay-ng.ini

CMD ["/conf/carbon-relay-ng.ini"]
`

**Comment by pawellesniewski** [comment]
```
\"exec: \\"/bin/carbon-relay-ng\\": permission denied\"\n"
```
It looks pretty obvious.

**Comment by Dieterbe** [comment]
why not use the dockerfile that comes with this project?
btw, we can set up something like circleci to auto push docker images to dockerhub. for free :)

**Comment by juaniterrarosa** [comment]
A only dockerfile was requested to me, thats the point :S 
Looks pretty obvious, as obvious like grant permissions?

**Comment by juaniterrarosa** [comment]
I finally run carbon in this way 

RUN ./carbon-relay-ng /etc/carbon-relay-ng.ini

**Comment by mhollick** [comment]
try sed -i ’s/RUN\ mv/ RUN install/‘ 


Matthew Hollick
mhollick@gmail.com <mailto:mhollick@gmail.com>
07903 447 669
