### ISSUE TITLE
Ubuntu Package Versions

### ISSUE THREAD

**Issue by directionless** [graphite-ng/carbon-relay-ng#142]
Hi! I was just looking at installing into ubuntu precise. I know precise is pretty old, but since it's a single go binary it seemed like a good bet.

I added https://packagecloud.io/app/raintank/raintank as documented, but I notice the version numbers are git shas:

```
vagrant@ubuntu-1204$ apt-cache show carbon-relay-ng  | grep Ver
Version: beaacc3-1
Version: ac73c5b-1
Version: 78c140e-1
Version: 12cb466-1
Version: 7e44d4b-1
Version: 5fed74e-1
Version: 5d8c9f3-1
```

As I understand it, this is against packaging guidelines, since we can't numerically sort those. 

Also, it doesn't work on precise. I can try to test on xenial as well
```
vagrant@ubuntu-1204$ sudo apt-get install carbon-relay-ng  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  carbon-relay-ng
0 upgraded, 1 newly installed, 0 to remove and 47 not upgraded.
Need to get 0 B/3,704 kB of archives.
After this operation, 13.2 MB of additional disk space will be used.
dpkg: error processing /var/cache/apt/archives/carbon-relay-ng_beaacc3-1_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'carbon-relay-ng':
 error in Version string 'beaacc3-1': version number does not start with digit
Errors were encountered while processing:
 /var/cache/apt/archives/carbon-relay-ng_beaacc3-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Dieterbe** [comment]
You're right. we don't support precise. 
in general I think we should, and try to, support the versions which are themselves also supported.
see https://wiki.ubuntu.com/Releases
this includes trusty and xenial (and we should add yakkety), but precise expired in aug 2014.

As for the versions.. I'm not sure what's the problem. the package builds use `git describe --tags --always | sed 's/^v//'` as version which should be strings like 0.7-55-g9c1de74, but instead we get just the last part, g9c1de74

it's as if the tags are not making it into the circleCI checkout or something.

**Comment by directionless** [comment]
No complaints about precise -- Though it's supported through April, it's ancient.

I think the lack of version is probably breaking most things trying to use the circleci builds. I don't see versions on any of the packages listed https://packagecloud.io/raintank/raintank

Building locally seems to work, but I don't know enough about circleci to easily debug it.

**Comment by petecheslock** [comment]
Tested trying to install on ubuntu trusty (14.04) and will get the same error.  
```
The following NEW packages will be installed:
  carbon-relay-ng
0 upgraded, 1 newly installed, 0 to remove and 57 not upgraded.
Need to get 3,704 kB of archives.
After this operation, 13.2 MB of additional disk space will be used.
Get:1 https://packagecloud.io/raintank/raintank/ubuntu/ trusty/main carbon-relay-ng amd64 d9baf0d-1 [3,704 kB]
Fetched 3,704 kB in 0s (3,724 kB/s)
dpkg: error processing archive /var/cache/apt/archives/carbon-relay-ng_d9baf0d-1_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'carbon-relay-ng':
 error in 'Version' field string 'd9baf0d-1': version number does not start with digit
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Dieterbe** [comment]
FYI I reached out to circleCI support last week and am waiting for a response

**Comment by kurtabersold** [comment]
Until the version numbers are fixed, the `--force-bad-version` option needs to be passed to dpkg.

This worked for me:

`sudo apt-get -o Dpkg::Options::="--force-bad-version" install carbon-relay-ng`

**Comment by directionless** [comment]
I think forcing the version numbers will do some weird things about ordering. The git shas aren't sorted

**Comment by woodsaj** [comment]
you need to use annotated tags.

**Comment by Dieterbe** [comment]
thanks @woodsaj that fixed it! I've released [v0.8](https://github.com/graphite-ng/carbon-relay-ng/releases/tag/v0.8) now, with fresh v0.8 packages. let me know how it goes folks.

**Comment by kurtabersold** [comment]
I agree. I think I lucked out though, the hash of the latest version was
the biggest bitwise. (Started with a d, I believe)

**Comment by Dieterbe** [comment]
apparently the old packages still sticking around in the repo caused trouble for people, so now i deleted all old packages from the repo. only >=0.8.7 remains.
