### ISSUE TITLE
How set destinations in relay to multiple hosts with carbon aggregators

### ISSUE THREAD

**Issue by rubenpapovyan** [graphite-ng/carbon-relay-ng#154]
hi,
Please help with relay config
Im running multiple hosts with carbon aggregator,
And I wonder if there is a way to distribute requests to aggregator multiple hosts from cargon-relay-ng. I mean the same way as carbon-relay dose (With consisting hashing to destinations, to make sure that each carbon-aggregator-ng always gets same metric )
See configuration diagram bellow (https://cdn177.picsart.com/223285132009202.png)

**Comment by Dieterbe** [comment]
what is aggregator-ng? anyway yes you can just add a route of type `consistentHashing`.

**Comment by Naishy** [comment]
I found the formatting took a bit of playing with before got it right but the following is an example with 2 hosts using `consistentHashing`:
`'addRoute consistentHashing graphite-default  192.168.0.10:2003 spool=true pickle=false  192.168.0.11:2003 spool=true pickle=false',`

**Note that you need two spaces before each IP address**
