### ISSUE TITLE
AMQP input?

### ISSUE THREAD

**Issue by jnjackins** [graphite-ng/carbon-relay-ng#159]
We have a large graphite installation that was bottlenecked at carbon-relay. We have improved our situation by incorporating carbon-relay-ng, but we now have the following unfortunate situation:

```
metrics via AQMP --> carbon-relay --> carbon-relay-ng --> carbon-cache:a
metrics via TCP --->                                  --> carbon-cache:b
                                                      --> ...
```

I would like to ditch the python version of carbon-relay entirely. I am considering extending carbon-relay-ng to also accept metrics via AMQP. Or perhaps the simpler solution is to write a standalone service to consume metrics from AMQP and hand them over to carbon-relay-ng. If I were to extend carbon-relay-ng, would you be interested in merging the change?

**Comment by Dieterbe** [comment]
I think it would be great to have this built-in instead of in yet another process. I would be very interested in the PR !
