### ISSUE TITLE
New release policy

### ISSUE THREAD

**Issue by matthew-hollick** [graphite-ng/carbon-relay-ng#166]
Hi,

When might the next release be?

Cheers

**Comment by Dieterbe** [comment]
I just published v0.8.5 just for you :) 
https://github.com/graphite-ng/carbon-relay-ng/releases/tag/v0.8.5

since it was retroactive, i had to create another commit and have that go through CI,
so the packages to install would be 0.8.5_1_g7cca199

**Comment by matthew-hollick** [comment]
Most awesome!
