### ISSUE TITLE
Question regarding addBlack regex

### ISSUE THREAD

**Issue by isavcic** [graphite-ng/carbon-relay-ng#170]
Hello @Dieterbe et al, I just wanted to ask: is addBlack regex performed only on the metric key *or* is it performed on the triplet of metric key, value and timestamp?

I'm asking because `\z` and `$` didn't work for me yesterday, so I tried `[[:space:]]+` instead, as such:

`^foo\.bar\.baz\.(?:p(?:50|75|98|99|999)|m(?:1|5|15|ean)_rate)[[:space:]]+`

and that worked.

If this is the case, maybe the docs should mention it, since perhaps other people spent their time as well, trying to figure out why don't `\z` and `$` work here.

Thanks for the info!

**Comment by isavcic** [comment]
CC @MilosD

**Comment by Dieterbe** [comment]
it used to be on the full message line (key, value and timestamp), which was rather silly, so it was changed in 58e357fc2ae4c18686f90f606fecfb2edc1b6775 to only look at the key which is what people expect.
please upgrade your relay and let me know whether `$` works (or `\z` which one is that again?).

**Comment by isavcic** [comment]
Thank you for the quick response! Indeed, yeah, our version is a couple of months old, I believe we don't have this change, we're going to doublecheck: https://github.com/graphite-ng/carbon-relay-ng/commit/58e357fc2ae4c18686f90f606fecfb2edc1b6775#diff-cce950b40a3962c50522cd22e55b0b51L69

**Comment by isavcic** [comment]
Seems to be working okay with a newer version, sorry for the noise!
