### ISSUE TITLE
carbon-relay-ng crashing due to bad unpickle

### ISSUE THREAD

**Issue by isavcic** [graphite-ng/carbon-relay-ng#171]
```
panic: runtime error: index out of range

goroutine 365 [running]:
panic(0x889ce0, 0xc42000e100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/graphite-ng/carbon-relay-ng/vendor/github.com/kisielk/og-rek.Decoder.Decode(0xc42255d260, 0xba4488, 0x0, 0x0, 0xc4224c2ab0, 0x0, 0x0, 0x0, 0xa)
	/home/ubuntu/go/src/github.com/graphite-ng/carbon-relay-ng/vendor/github.com/kisielk/og-rek/ogorek.go:249 +0x1d91
github.com/graphite-ng/carbon-relay-ng/input.(*Pickle).Handle(0xc4201a0600, 0xb64820, 0xc420140010)
	/home/ubuntu/go/src/github.com/graphite-ng/carbon-relay-ng/input/pickle.go:76 +0x6ab
created by github.com/graphite-ng/carbon-relay-ng/input.accept
	/home/ubuntu/go/src/github.com/graphite-ng/carbon-relay-ng/input/listen.go:38 +0x7a
```
Given that kisielk refactored his code to address these `index out of range` panics[1], perhaps this new version should be pulled in?

Unfortunately, at this moment, I don't have an example of this bad data, nor information on whether the abovementioned fix from kisielk would work. I'll try to build a separate carbon-relay-ng instance with this new version and give it a try.

And again, thanks for your great work on this, @Dieterbe.

[1] https://github.com/kisielk/og-rek/issues/30

**Comment by Dieterbe** [comment]
>  I'll try to build a separate carbon-relay-ng instance with this new version and give it a try.

cool let me know how it goes! if you're having a hard time building the relay or something, let me know
