### ISSUE TITLE
New metric aggregation: "delta"

### ISSUE THREAD

**Issue by guillaumeautran** [graphite-ng/carbon-relay-ng#189]
The relay aggregator currently support 'sum', 'min', 'max' and 'avg' as type of aggregations. It would be useful to expand the list to also support a 'delta' type of aggregation which will report the difference between 'min' /  'max' of a given metric within the reporting period.

**Comment by Dieterbe** [comment]
hm yes, and standard deviation also :)

**Comment by Dieterbe** [comment]
thanks guillaume!
