### ISSUE TITLE
Unable to deserialize the kafka messages with Java client

### ISSUE THREAD

**Issue by jdbranham** [graphite-ng/carbon-relay-ng#204]
I've tried different Codecs in the kafkaMdm route configuration [none, snappy, gzip], but the message always looks the same to my Kafka consumer, and I'm not sure how to deserialize the bytes.

The data looks like this if I decode the bytes as a UTF-8 string -

��Id�"1.93031eafed808bc1124e859b2986241a�OrgId�Name�0prod.xxx_com.cpu.0.cpu.user�Metric�0prod.xxx_com.cpu.0.cpu.user�Interval�Value�@)���۹ФUnit�unknown�Time�YS���Mtype�gauge�Tags�

When I change the codec, it doesn't look like it's actually changing anything in the message payload.

Any ideas?

**Comment by jdbranham** [comment]
Here is my route configuration -

```
[[route]]
# Kafka route for analytics
type = 'kafkaMdm'
key = 'kafka'
topic = 'metrics'
partitionBy = 'bySeries'
orgId = 1
schemasFile = '/tools/graphite/conf/storage-schemas.conf'
subStr = 'cpu'
codec = 'none'
broker = 'brokerserver01:9092'
spool = true

```

**Comment by Dieterbe** [comment]
the codec is just transport-layer compression and doesn't change the actual message. the message is messagepack encoded MetricData as defined on https://github.com/raintank/schema/blob/master/metric.go#L35

**Comment by Dieterbe** [comment]
what are you trying to do ? there's a few kafka-mdm tools in https://github.com/raintank/metrictank/tree/master/cmd that are good examples of consuming the data.

**Comment by jdbranham** [comment]
Thanks Dieter - 
I'm pumping the data into Kafka to use Flink for anomaly detection. When I unpack the message in the java app, it looks like platform specific encoding.
I'm packaging up the Flink jar to see if the results are different on Linux [same as message source].

**Comment by jdbranham** [comment]
Looks like it should be UTF-8 across both servers and my local Windows dev machine, but still comes back with some unidentified characters.

**Comment by jdbranham** [comment]
Please excuse my ignorance of golang [and the imported libraries], but would it be possible to send a pure json payload to the kafka broker?
Or does it need to be serialized another way before sending?

**Comment by jdbranham** [comment]
It looks like the payload is already a serialized json object if I'm understanding this code block correctly. I just don't know why the same function doesn't work on my system using Java -
[bytes -> String -> object]

https://github.com/raintank/schema/blob/master/metric.go#L180

**Comment by jdbranham** [comment]
I've traced the messages back and I'm pretty sure the byte encoding being sent from the producer [sarama] is problematic for my kafka consumer.
I can use a byte array deserializer, but the byte values don't make sense to me. 

Maybe there is a sequence I can use to take apart this payload?

The key is deserialized fine, but the value is not.

**Comment by Dieterbe** [comment]
> would it be possible to send a pure json payload to the kafka broker?

it would be, but that would be inefficient. messagepack is comparable to json, except more efficient.

> It looks like the payload is already a serialized json object if I'm understanding this code block correctly. I just don't know why the same function doesn't work on my system using Java -
[bytes -> String -> object]

it's not. it's messagepack

> https://github.com/raintank/schema/blob/master/metric.go#L180
> Called from here -
> https://github.com/raintank/metrictank/blob/master/input/kafkamdm/kafkamdm.go#L292

this line does a messagepack unmarshal of a MetricData structure, the MetricDefinition From JSON you're linking to has nothing to do with this.

**Comment by jdbranham** [comment]
Thanks for the feedback @Dieterbe 

The issue I'm having is related to the unmarshal of the messagepack.
I'm super noob at golang [only experience is digging into grafana stuff]
Could you link me to where the messagepack byte sequence is created from the metric data?

I hope to reverse this process in my kafka deserializer.

**Comment by jdbranham** [comment]
Is that here?

https://github.com/raintank/schema/blob/master/msg/msg.go#L67

**Comment by jdbranham** [comment]
I decided to build a carbon proxy/relay in Java. It would still be nice to add messagepack support to it.

https://github.com/savantly-net/carbon-proxy

**Comment by sternr** [comment]
We're having the almost exact same fun, we're trying to produce a messagepack object using java kafka client and no matter what we do metrictank would give:

kafka-mdm decode error, skipping message. msgp: attemp
ted to decode type "uint" with method for "int"

Which is upsetting since we tried to consume and compare the binary and they look pretty much the same...

**Comment by sternr** [comment]
OK, so we found the problem, it seems like metricTank requires the time property of the message object to be serialized as INT32, however the packInt (or packLong) will always try to optimize it into UINT32 which metricTank doesnt like. so we had to use addPayload and serialize MessagePacker.Code.INT32, and then the actual 4 bytes of the time property.

Eat that MetricTank
