### ISSUE TITLE
Version in help output

### ISSUE THREAD

**Issue by matthew-hollick** [graphite-ng/carbon-relay-ng#205]
Hi,

It would be great if something like this worked:

```
$ ./carbon-relay-ng -version
0.9.1
$
```

Cheers!

**Comment by Dieterbe** [comment]
I agree, we have a pretty neat mechanism in https://github.com/raintank/metrictank to do that, and i want it here too :)

**Comment by Dieterbe** [comment]
fixed in 295c2041fecc2cc727f1e415f5599419a8070c42
