### ISSUE TITLE
carbon-relay-ng does not create the `/var/run/carbon-relay-ng` directory properly

### ISSUE THREAD

**Issue by guillaumeautran** [graphite-ng/carbon-relay-ng#212]
On linux system where the `/run` directory is a tmpfs, carbon relay should properly configure the `tmpfiles.d` entry to create its working directory. 
Presently, the `tmpfiles.d` entry is created but the configuration specifies that the directory ownership should be `carbon-relay-ng:carbon-relay-ng` which neither the owner or the group exist. 
this cause the directory to not be created on on boot and consequently prevent carbon-relay from starting.

**Comment by choffee** [comment]
Should the process run as carbon-relay-ng? I can't see a reason it needs to run as root.

**Comment by guillaumeautran** [comment]
It does not need to run as root (as long as it does not use privileged ports; which it does not by default). My PR does address this and make carbon relay start as a non-root user.

**Comment by Dieterbe** [comment]
@guillaumeautran is this still an issue?

**Comment by guillaumeautran** [comment]
This can be closed after #213 was merged. 
Thanks.
