### ISSUE TITLE
Should tags be included in the metric path metrics2.0 when viewing with graphite-web

### ISSUE THREAD

**Issue by tehlers320** [graphite-ng/carbon-relay-ng#231]
Should foo.bar.UNIT=no.bar appear in graphite as "foo.bar.UNIT=no.bar". 

Reproduce procedures. 

`echo "foo.bar.UNIT=no.bar 4 `date +%s`" | nc -w2 localhost 2003`
```
rpm -qa |grep carbon
carbon-relay-ng-0.9.3_1_g351f807-1.x86_64
```

config is standard except that we use kafkaMdm

Results:
![screen shot 2017-10-20 at 3 35 09 pm](https://user-images.githubusercontent.com/16598119/31840752-4c969db6-b5ac-11e7-8fa2-bd470de63724.png)

**Comment by Dieterbe** [comment]
Isn't this normal ? What do you want instead ?

**Comment by tehlers320** [comment]
I'm not sure, is it? This can be closed, we are just experimenting with metrics2.0 i'm not sure how it should look. I wasn't sure if it was suppose to make it look "traditional" on the graphite tree or not. I think you answered that question.
