### ISSUE TITLE
Post install script: adduser: unrecognized option '--quiet'

### ISSUE THREAD

**Issue by Duologic** [graphite-ng/carbon-relay-ng#232]
When installing the RPM on Centos/7 I get the following error:

```
adduser: unrecognized option '--quiet'
```

`--group` doesn't seem to exist either, should be replaced by `--user-group`.

I install it from https://packagecloud.io/raintank/raintank

Should this be fixed in `examples/after_install.sh`?

I would make a pull request but I don't have RedHat installation ready to test. Anyone who can output me `useradd --help` and `adduser --help` from RedHat?

**Comment by Duologic** [comment]
`--group` doesn't seem to exist either.

**Comment by Dieterbe** [comment]
yeah, but we should make sure not to break the debian one. if they need different args we should have different after_install.sh files for the distro's
