### ISSUE TITLE
/var/run/carbon-relay-ng gets removed on reboot

### ISSUE THREAD

**Issue by Duologic** [graphite-ng/carbon-relay-ng#234]
It seems that after reboot, the home directory gets removed. I see this on Centos/7.

I've resolved this by creating `/etc/tmpfiles.d/carbon-relay-ng.conf`:

```
D /var/run/carbon-relay-ng 0755 carbon-relay-ng carbon-relay-ng
```

Not sure if this can be incorporated into the RPM package.

**Comment by Dieterbe** [comment]
via #213 we recently introduced a carbon-relay-ng-tmpfiles.conf but looking at the makefile, it seems it's only installed for debian. can you tweak the makefile, test the package on centos7 and file a PR ? thanks ! :) cc @guillaumeautran

**Comment by Duologic** [comment]
Sure, I'll have a look.

**Comment by Duologic** [comment]
The config looks like it should work on centos/7 too.
