### ISSUE TITLE
Blacklist does not work when inserted below amqp in ini

### ISSUE THREAD

**Issue by Jrmcneil** [graphite-ng/carbon-relay-ng#237]
I've found that the relay does not blacklist metrics if the blacklist array is located below the amqp variables in carbon-relay-ng.ini (which is the ordering in the example ini)

Below is a pared-down version of the ini provided in /examples. I've set the route destination to a port on my public IP:

```
instance = "${HOST}"
max_procs = 2

admin_addr = "0.0.0.0:2004"
http_addr = "0.0.0.0:8081"
spool_dir = "spool"
pid_file = "carbon-relay-ng.pid"

log_level = "notice"

validation_level_legacy = "medium"
validate_order = false

bad_metrics_max_age = "24h"

listen_addr = "0.0.0.0:2003"

pickle_addr = "0.0.0.0:2013"

[amqp]
amqp_enabled = false

blacklist = [
            'prefix collectd.localhost',
            'regex ^foo\..*'
]

[[route]]
key = 'carbon-default'
type = 'sendAllMatch'
destinations = [
  'x.x.x.x:3003 spool=false pickle=false'
]

[instrumentation]
graphite_addr = "localhost:2003"
graphite_interval = 1000  # in ms
```

Load an image of carbon-relay-ng with this ini
```
docker run -it --rm -p 2003:2003 -p 8081:8081 -v $(pwd)/carbon-relay-ng.ini:/conf/carbon-relay-ng.ini raintank/carbon-relay-ng
```

Listen on 3003
```
nc -l 3003 | grep -e foo -e bar
```

And write a few fake metrics to 2003
```
echo "bar.something 1 `date +%s`" | nc -c 127.0.0.1 2003
echo "foo.something 1 `date +%s`" | nc -c 127.0.0.1 2003
```

I see both metrics output by my listener. But move the blacklist array above the [ampq] line and try again and the blacklist works as expected.

**Comment by randallt** [comment]
I have confirmed this as well. It was very confusing at first. Is this a feature, such that a blacklist array can be defined underneath any section? Or is it a bug in the example conf file?

**Comment by Dieterbe** [comment]
this was an oversight in the example configs. thanks for reporting and helping with the troubleshooting.
it's kind of annoying, but the way our config parser works, any non-section settings must come before sections
