### ISSUE TITLE
Release for debian/stretch

### ISSUE THREAD

**Issue by daks** [graphite-ng/carbon-relay-ng#246]
Hello,

do you plan to release carbon-relay-ng packages for debian/stretch?

**Comment by Dieterbe** [comment]
totally!
TBH i was not aware of a new debian release. we have to look into what we need to do to support it.

**Comment by daks** [comment]
Ok. I'm mostly interested by the built packages on packagecloud.

**Comment by Dieterbe** [comment]
Hi Éric, I just pushed a change that pushes our deb packages into the debian/stretch (and buster) repos.
stay tuned for the build to complete and the package to become available and please let me know how it goes!
