### ISSUE TITLE
carbon-relay-ng Configuration

### ISSUE THREAD

**Issue by daks** [graphite-ng/carbon-relay-ng#247]
Hello,

I just started evaluating carbon-relay-ng and I have difficulties to understand where configuration should be.
Three methods exists to configure carbon-relay-ng: config file, HTTP, and CLI. But I'm not sure if they are equivalent.

- are HTTP and CLI ways to modify running configuration? But are these changes saved somewhere (in config file I imagine) and permanent?
- when restarting/reloading processus, is the config file the only configuration read and applied?
- some tests changing routes on HTTP interface seems to not work, is this normal?

Thanks

**Comment by Dieterbe** [comment]
with cli i presume you mean the telnet interface.

> are HTTP and CLI ways to modify running configuration

yes

> But are these changes saved somewhere (in config file I imagine) and permanent?

no. up to you to make changes in the config file accordingly.

note that web and telnet interfaces may have some rough edges. to be safe, better update config file and restart.

> when restarting/reloading processus, is the config file the only configuration read and applied?

yes

**Comment by daks** [comment]
So http and telnet interfaces are aimed for temporary config changes, but permanent ones must be set in the config file. Ok, I understand.

Last question: when you talk about 'restart', is `systemctl restart carbon-relay-ng` the way to go (I use Debian 9 package with systemd unit), or is there a better command line option to reload/keep current connections alive?

**Comment by Dieterbe** [comment]
unfortunately, must restart the process. we used to have a hot-reload thing but it didn't work reliably. the command looks good to me

**Comment by daks** [comment]
Thanks for your answers.
