### ISSUE TITLE
Questions for Disk Spooling Feature.

### ISSUE THREAD

**Issue by yunstanford** [graphite-ng/carbon-relay-ng#249]
1. Does Carbon-relay-ng remove disk spooling files after resending them back to destination ?
2. I'm still seeing data gaps after destination comes back... not sure if spooling feature works fine. And i observed that the `dest metric drops` metrics are all zero, which should mean that there is no metric loss. But i did see data gaps.
3. The default value for max filesize for spool files is 200MB, what if it needs more than 200MB ? In that case, does carbon-relay-ng just drop those additional metrics due to the 200MB limit ?
4. Does Carbon-relay-ng do a batch job for resending spooled metrics when destination comes back ? if so, what is batch size ? is it configurable ?

Thanks.

**Comment by yunstanford** [comment]
5. how does the spooling file look like ? is it sth. like `circular buffer` ?

**Comment by yunstanford** [comment]
6. I observed `conn flush durations` overflow max during destination is down.. does it matter ?

**Comment by maltris** [comment]
Good handling of valid questions by closing the ticket, thanks!
