### ISSUE TITLE
Package for Debian Jessie is not installable

### ISSUE THREAD

**Issue by daks** [graphite-ng/carbon-relay-ng#252]
Hello,

I'm trying to install carbon-relay-ng on Debian Jessie, using raintank repository. I see a bunch of versions:

```
# apt-cache policy carbon-relay-ng
carbon-relay-ng:
  Installed: (none)
  Candidate: d57b815-1
  Version table:
     d57b815-1 0
        500 https://packagecloud.io/raintank/raintank/debian/ jessie/main amd64 Packages
     c6931e0-1 0
        500 https://packagecloud.io/raintank/raintank/debian/ jessie/main amd64 Packages
     5ba53bd-1 0
        500 https://packagecloud.io/raintank/raintank/debian/ jessie/main amd64 Packages
     0.9.4-1-gcf65529-1 0
        500 https://packagecloud.io/raintank/raintank/debian/ jessie/main amd64 Packages
     0.9.4-1 0
        500 https://packagecloud.io/raintank/raintank/debian/ jessie/main amd64 Packages
...
```

but I can't install it, an error happens about version number. The last one is `d57b815-1` and I think is not compliant with Debian guidelines.

```
# apt-get install carbon-relay-ng
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  carbon-relay-ng
0 upgraded, 1 newly installed, 0 to remove and 88 not upgraded.
Need to get 0 B/4218 kB of archives.
After this operation, 13.5 MB of additional disk space will be used.
dpkg: error processing archive /var/cache/apt/archives/carbon-relay-ng_d57b815-1_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'carbon-relay-ng':
 error in 'Version' field string 'd57b815-1': version number does not start with digit
Errors were encountered while processing:
 /var/cache/apt/archives/carbon-relay-ng_d57b815-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by ftieben** [comment]
This will also affect Ubuntu:

`dpkg: error processing archive /var/cache/apt/archives/carbon-relay-ng_d57b815-1_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'carbon-relay-ng':
 error in 'Version' field string 'd57b815-1': version number does not start with digit
`

**Comment by guillaumeautran** [comment]
I don't think those are official release (instead just dev snapshots). Please refer to the [release page](https://github.com/graphite-ng/carbon-relay-ng/releases) and install only release versions.

**Comment by daks** [comment]
What is strange is that stretch does not have the same versions and especially those snapshots versions.
I'll adapt my automation code to add a constraint for version.

**Comment by Dieterbe** [comment]
> I don't think those are official release (instead just dev snapshots)

note that master is considered stable, so any released package should work (including builds in between official "releases") and if not, it is a valid bug

**Comment by Dieterbe** [comment]
> What is strange is that stretch does not have the same versions and especially those snapshots versions.

that's because we only just started creating stretch packages as of #246 , as of then on forward, we create the same package versions

**Comment by daks** [comment]
Thanks for the information, what I mean is that on stretch I can just `apt-get install carbon-relay-ng` which does not works on jessie due to this number version not compatible with debian guidelines. It doesn't depend on the master branch status.

**Comment by Dieterbe** [comment]
the way our build scripts work, any version should always start with a number.
e.g. carbon-relay-ng_0.9.4-1-gcf65529-1_amd64.deb
for some reason, some badly formed ones snuck in, such as carbon-relay-ng_5ba53bd-1_amd64.deb
I don't know why. this shouldn't happen.
either way i've deleted the malformed ones.

does it work now?

**Comment by daks** [comment]
@Dieterbe it works, thanks for your reactivity.
