### ISSUE TITLE
what does the status_is_incomingRT metric mean ?

### ISSUE THREAD

**Issue by yunstanford** [graphite-ng/carbon-relay-ng#253]
how can i understand the `status_is_incomingRT` metric ?

**Comment by Dieterbe** [comment]
2 kinds of metrics go into the spool.
RT (realtime), coming from the destination, when it can't send metrics to the remote endpoint
bulk: for redo buffers, when the destination is offline and the relay doesn't know of the last data whether or not it is received by the remote, so it keeps a "redo buffer" for that case, which it flushes in bulk.
