### ISSUE TITLE
Does carbon-relay-ng support pure kafka?

### ISSUE THREAD

**Issue by keyboardfann** [graphite-ng/carbon-relay-ng#281]
What I want is send graphite metrics to kafka  and get the metrics out to do something, 
I send graphite metrics to carbon-relay-ng and it route metrics to kafka, but when I get it out use kafka-consumer command, it show special character. Is there config error or carbon-relay-ng support pure kafka0.10.2?

carbon-relay-ng.conf,  carbon-relay-ng will send to kafka metrics topic
```[[route]]
# Kafka route for analytics
type = 'kafkaMdm'
key = 'kafka'
topic = 'metrics'
brokers = ["tng1512:9092"]
partitionBy = 'bySeries'
regex = '^test.fanntest*'
orgId = 1
schemasFile = '/opt/graphite/conf/storage-schemas.conf'
codec = 'none'
spool = true
```

Test script to send metrics to carbon-relay-ng
```
[root@tng1519 ~]# cat test.sh 
PORT=2201
SERVER=tng1519
echo "test.fanntest1.aa 4 `date +%s`" | nc  ${SERVER} ${PORT}
```

Use kafka-consumer to consume the metrics
```
[root@tng1512 ~]# kafka-console-consumer --bootstrap-server tng1512:9092 --topic metrics
¢Idע1.8262150eab407e39d6292de3603e67f7¥OrgId¤Name².test.fanntest1.aa¦Metric².test.fanntest1.aa¨Interval<¥Valueʀ¤Unit§unknown¤Timeћ4¥Mtype¥gauge¤Tags 
```
carbon-relay-ng log
```
[root@tng1519 ~]# systemctl status carbon-relay-ng
● carbon-relay-ng.service - Starts and stops carbon-relay-ng on this system
   Loaded: loaded (/usr/lib/systemd/system/carbon-relay-ng.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-06-11 11:48:55 CST; 2h 15min ago
     Docs: https://github.com/graphite-ng/carbon-relay-ng/tree/master/docs
 Main PID: 10013 (carbon-relay-ng)
   CGroup: /system.slice/carbon-relay-ng.service
           └─10013 /usr/bin/carbon-relay-ng /etc/carbon-relay-ng/carbon-relay-ng.conf

Jun 11 11:49:00 tng1519 carbon-relay-ng[10013]: 11:49:00.450738 ▶ INFO  KafkaMdm "kafka": sent 1 metrics in 2.759072ms - msg size 163
Jun 11 11:50:51 tng1519 carbon-relay-ng[10013]: 11:50:51.363360 ▶ INFO  kafkaMdm "kafka": sending to dest [tng1512:9092]: .test.fanntest1.aa 4 1528689051
Jun 11 11:50:51 tng1519 carbon-relay-ng[10013]: 11:50:51.449513 ▶ INFO  KafkaMdm "kafka": sent 1 metrics in 1.594057ms - msg size 163
Jun 11 11:55:49 tng1519 carbon-relay-ng[10013]: 11:55:49.972212 ▶ INFO  kafkaMdm "kafka": sending to dest [tng1512:9092]: .test.fanntest1.aa 4 1528689349
Jun 11 11:55:50 tng1519 carbon-relay-ng[10013]: 11:55:50.449421 ▶ INFO  KafkaMdm "kafka": sent 1 metrics in 1.533021ms - msg size 163
Jun 11 11:55:50 tng1519 carbon-relay-ng[10013]: 11:55:50.570083 ▶ INFO  kafkaMdm "kafka": sending to dest [tng1512:9092]: .test.fanntest1.aa 4 1528689350
Jun 11 11:55:50 tng1519 carbon-relay-ng[10013]: 11:55:50.920483 ▶ INFO  kafkaMdm "kafka": sending to dest [tng1512:9092]: .test.fanntest1.aa 4 1528689350
Jun 11 11:55:50 tng1519 carbon-relay-ng[10013]: 11:55:50.949359 ▶ INFO  KafkaMdm "kafka": sent 2 metrics in 1.420889ms - msg size 326
Jun 11 13:57:08 tng1519 carbon-relay-ng[10013]: 13:57:08.875269 ▶ INFO  kafkaMdm "kafka": sending to dest [tng1512:9092]: .test.fanntest1.aa 4 1528696628
Jun 11 13:57:09 tng1519 carbon-relay-ng[10013]: 13:57:09.052439 ▶ INFO  KafkaMdm "kafka": sent 1 metrics in 104.474347ms - msg size 163

```

**Comment by Dieterbe** [comment]
what do you mean with "pure" ? messages need to be encoded somehow, and carbon-relay-ng uses a messagepack format. is there another de-facto format for carbon over kafka?

**Comment by keyboardfann** [comment]
HI @Dieterbe ,
    Thank you for the replying.  Can I send plaintext metrics -> carbon-relay-ng -> kafka ->kafka consumer get plaintext metrics?  I only want kafka as a queue purpose and get the metrics out the same plaintext graphite format, then I can do something

**Comment by Dieterbe** [comment]
carbon-relay-ng does not support kafka as a transport for plain ascii encoded messages.
support could be added, but i have no interest in that.

**Comment by ivanich** [comment]
Actually it would be useful to have such feature in carbon-relay-ng, we're trying to replace our graphite stack with metrictank, the problem is that all our apps send metrics to graphite in plain ascii encoded messages and we cannot change that, basically we could use builtin metrictank carbon input plugin but in that case we cannot properly setup a cluster without kafka.
Our current schema is app -> carbon-c-relay -> go-carbon
we would like change it to :
app -> carbon-relay-ng -> kafka -> metrictank

**Comment by ivanich** [comment]
I'm not quite understand how to achieve this

> Note that carbon-relay-ng can be used to pipe a carbon stream into Kafka.

From https://github.com/grafana/metrictank/blob/master/docs/inputs.md#kafka-mdm-recommended
