### ISSUE TITLE
feature request: ability to reconnect destinations without restarting

### ISSUE THREAD

**Issue by randallt** [graphite-ng/carbon-relay-ng#290]
I have an issue where I sometimes need carbon-relay-ng to reconnect to certain destinations. Currently, I've been restarting the service, but because of aggregation in use, I lose metrics. I'm looking for a way to do this without restarting the service. I looked at the admin interface for this, but it looks like the only way would be to modify the destinations, which is less than ideal.

**Comment by Dieterbe** [comment]
if the tcp connection closes, destinations should reconnect automatically

**Comment by woodsaj** [comment]
@randallt what type of destination are you using?  They all should automatically reconnect when connections drop.

**Comment by randallt** [comment]
Correct. However, I need this to be able to rebalance connections on a load balancer. So connections have already reconnected due to drops, but new connections have connected in a non-balanced way. Once maintenance/outage is over, I'd like to be able to reconnect the connections to go back to a well-balanced status.

**Comment by woodsaj** [comment]
duplicate #278 ?
