### ISSUE TITLE
Remove usage of go-bindata

### ISSUE THREAD

**Issue by duckie** [graphite-ng/carbon-relay-ng#295]
go-bindata is no longer maintained, so maybe carbon-relay-ng should not use it anymore.

**Comment by Dieterbe** [comment]
hi @duckie thanks for the report. good to know, but as long as we have no issues with bindata it's not worth the hassle of changing over to something else.

**Comment by woodsaj** [comment]
@dieter i think we should just update the build scripts to use https://github.com/go-bindata/go-bindata instead.  I haven't check but i would assume it would just work.

**Comment by Dieterbe** [comment]
see #297
