### ISSUE TITLE
UDP metrics not consumed in version 0.9.1

### ISSUE THREAD

**Issue by xkilian** [graphite-ng/carbon-relay-ng#298]
When sending udp legacy graphite format either locally or remote carbon-relay-ng is not processing the metrics.
The service is listening on udp 2013, but no log entries corresponding to my metric is seen in the /var/log/syslog. Even if I set carbon-relay-ng in debug mode.

If I send the exact same metrics to the tcp port 2013, it works fine.

I will try to upgrade to the newest version, but the release notes do not refer to any issues with udp metrics.

**Comment by DanCech** [comment]
Are you sure that the metrics are actually reaching carbon-relay-ng? You can use a tool like tcpdump to examine the traffic and see whether you see any packets coming in

**Comment by xkilian** [comment]
Yes, metrics are reaching the relay using tcpdump.
I have noticed that if metrics are appended with \n they will get consumed, if not they are silently dropped.
Having a \n is not part of the graphite spec and is not also documented in the carbon-relay-ng documentation.

**Comment by xkilian** [comment]
This is for single metrics per UDP packet.

**Comment by woodsaj** [comment]
https://graphite.readthedocs.io/en/latest/feeding-carbon.html#step-3-understanding-the-graphite-message-format

> Graphite understands messages with this format:
```
metric_path value timestamp\n
```

**Comment by xkilian** [comment]
My mistake, I should have submitted with \n out of the box. 

Should carbon-relay-ng give some type of feedback if it receives data that does not have a \n? At least increment one of the invalid format counters.

**Comment by xkilian** [comment]
Though to be faire the documentation also has this to say, notice it does not mention a \n:  https://graphite.readthedocs.io/en/latest/feeding-carbon.html

The plaintext protocol

The plaintext protocol is the most straightforward protocol supported by Carbon.

The data sent must be in the following format: <metric path> <metric value> <metric timestamp>. Carbon will then help translate this line of text into a metric that the web interface and Whisper understand.

**Comment by efficks** [comment]
@woodsaj This doc does not mention the '\n' char too. There's multiple place where it's not documented. Also, the old carbon-relay support the '\n' omission.

**Comment by efficks** [comment]
@woodsaj Also, carbon-relay supports the absence of \n

**Comment by DanCech** [comment]
It looks like this is restricted to UDP, TCP does work with and without a newline, and UDP works with a newline.  I suspect it's due to the way that the golang implementation handles the UDP connection, will dig into it further as part of #286

**Comment by Dieterbe** [comment]
@xkilian have you tried a recent version? I believe this should be fixed now. @DanCech correct me if i'm wrong.

**Comment by DanCech** [comment]
Yes, this was fixed in #286
