### ISSUE TITLE
Recommended config for pickeled and plaintext protocols

### ISSUE THREAD

**Issue by nisc-acooper** [graphite-ng/carbon-relay-ng#299]
We have attempted to allow both pickeled and plaintext protocols through carbon-relay-ng to go-carbon backends.  We successfully have plaintext relaying, but when trying to send pickeled, the data never shows up in go-carbon.   

Does carbon-relay-ng parse the pickeled data and transform into plaintext to be sent to backend go-carbon, or do we need to setup a "pickled only" route to a go-carbon pickeled port?

**Comment by DanCech** [comment]
carbon-relay-ng will decode all the data sent to it via both plain and pickle inputs and pass it through the same processing pipeline and output plugins you define, regardless of the input format.

If you're having issues you should definitely check the logs for any error messages related to the pickle input.

**Comment by Dieterbe** [comment]
@nisc-acooper please confirm if this is still the case and if so, provide more details (config file, how you send data, go-carbon config, any errors seen) and we can take a look.
