### ISSUE TITLE
Can carbon-relay-ng blackhole metrics instead of blacklist/reject them ?

### ISSUE THREAD

**Issue by kimattree** [graphite-ng/carbon-relay-ng#308]
This would be an awesome feature - I have some spring containers that send metric information to graphite, but since carbon-relay-ng rejects instead of accepting and discarding, the metric queues in the containers grow and grow until heap expires.

I know carbon-c-relay has this functionality, but I really like the NG frontend and ease of configurability.

Possible ?

**Comment by Dieterbe** [comment]
not sure what you mean.
the blacklist functionality effectively discards matching series after accepting them.

or do you mean that the metrics don't even pass validation before they make it to the blacklist?

**Comment by kimattree** [comment]
Metrics seem to getting rejected (instead of discarded) by carbon-relay-ng - they end up sitting in a queue on the pod.

The behaviour is somewhat like the difference between iptables DROP and REJECT, one sends a response and the other just silently drops traffic.

From what I'm seeing its like my metric processor in the pod is getting a message back saying "sorry this string is rejected". All other metrics from that same pod that are passed through the blacklist are cleared from the pod metric backlog, and appear in graphite/grafana.

As a test, I removed the blacklist from the frontend, and then a massive flood of updates came through (matching the previous blacklist reject regex) until I re-enabled the blacklist regex again. This is why I'm saying this feels like carbon-relay-ng is rejecting metrics (with an API message or something saying that its not accepted) instead of just accepting and discarding them.

**Comment by woodsaj** [comment]
@kimattree there is no feedback between carbon-relay-ng and clients.  Clients communicate with crng, but crng does not ever send any information back.

blacklists are evaluated by the core Dispatch() function.  This function does not provide a return value so input plugins have know way of knowing whether metrics were dropped or not.

**Comment by kimattree** [comment]
Then its most definately something on my pod side - thanks for the feedback.
