### ISSUE TITLE
[v0.11.0] pickle handler: invalid payload prefix

### ISSUE THREAD

**Issue by hamelg** [graphite-ng/carbon-relay-ng#340]
Hello,
Today, I've upgraded my carbon-relay-ng from 0.9.4 to 0.11.0. I have a bunch of servers which send metrics via pickle protocol with the diamond service. With the v0.11.0, all connections fail with these errors in carbon-relay-ng logs.

```
[WARNING] pickle handler for xxx returned: couldn't read payload length: read tcp xxxxx:2014->yyyyyy:57132: i/o timeout. closing conn
[WARNING] pickle handler for zzzzzz:54562 returned: invalid payload prefix. closing conn
[WARNING] pickle handler for zzzzzz:57034 returned: invalid payload prefix. closing conn
[WARNING] pickle handler for zzzzzz:39084 returned: invalid payload prefix. closing conn
```
I have rollbacked to v0.9.4.
Any ideas about this breakage ?
Thank you.

**Comment by Dieterbe** [comment]
so diamond sends the data? which version? can you perhaps share your config?

**Comment by hamelg** [comment]
diamond v4.0.809 (build date 19/1/2018 from master).
Metrics are sent with the handler GraphitePickleHandler to relayng:2014.

On the carbon-relay-ng.conf side
```

listen_addr = "relayng:2013"
pickle_addr = "relayng:2014"
admin_addr = "localhost:2010"
http_addr = "localhost:2011"

validation_level_legacy = "medium"
validation_level_m20 = "medium"
validate_order = false
```

**Comment by DanCech** [comment]
That would typically indicate that the producer is sending a non-standard pickle request, the previous version was more permissive and didn't validate that the pickle data included a valid prefix.  The first thing we'll need to figure out is what diamond is sending in the pickle stream.

**Comment by hamelg** [comment]
The workaround would be reverting the commit https://github.com/graphite-ng/carbon-relay-ng/commit/592c81f2591db6460aba3eae543f60d8ad1b7000, is it safe ?

**Comment by DanCech** [comment]
I wouldn't revert the commit, you could comment out the `if` block on lines 78 through 82 where it checks the prefix.

The graphite documentation does actually show that the protocol version should be set to `2` in the pickle example, though it's not explicitly called out in the text:

https://graphite.readthedocs.io/en/latest/feeding-carbon.html#the-pickle-protocol

Right now crng will work fine with protocol version 2, 3 or 4, it's 0 and 1 that are the problem.

**Comment by Dieterbe** [comment]
@hamelg this should be fixed now.

**Comment by hamelg** [comment]
Sorry for my late feedback.
I have tested the 3 latest commits related to pickle management and it sill doesn't work.
All metrics received via pickle protocol are rejected with these errors in logs.

with 0.11.0-1-gdd602b0 and 0.11.0-4-g6f7fff5
[WARNING] pickle handler for 10.xx.xx.xx:41212 returned: couldn't read payload length: read tcp 10.xx.xx.xx:2014->10.xx.xx.xx:41212: i/o timeout. closing conn

**Comment by Dieterbe** [comment]
Hmm now it looks like a network problem . Works fine with 0.9.4?

**Comment by hamelg** [comment]
Yes, works fine in 0.9.4.

**Comment by DanCech** [comment]
That is strange, the code that reads the payload length hasn't changed between 0.9.4 and master.

**Comment by hamelg** [comment]
I did a git bisect.
The offending commit is : 
[8c7e8458ebd7737a50bffe4badb216d343a55dbb] don't accept pickle payloads over 500MB, don't read too much from connection

**Comment by hamelg** [comment]
It was another issue : the default value of the setting pickle_read_timeout was too low.
Now, all works very fine :)
Sorry for the noise. Thanks much for all.
