### ISSUE TITLE
Config File When Using Carbon-Relay-NG Docker Image

### ISSUE THREAD

**Issue by plankconst** [graphite-ng/carbon-relay-ng#345]
How does one edit the configuration file when using the Carbon-Relay-NG Docker Image?

> https://github.com/graphite-ng/carbon-relay-ng/blob/master/examples/carbon-relay-ng.ini

When I run the image, I see it listening on 0.0.0.0. But I want to set the IP addresses instead to my public IP address. 

> 2019-03-15 14:34:46.088 [INFO] listening on 0.0.0.0:2003/tcp
> 2019-03-15 14:34:46.088 [INFO] listening on 0.0.0.0:2003/udp
> 2019-03-15 14:34:46.088 [INFO] listening on 0.0.0.0:2013/tcp
> 2019-03-15 14:34:46.088 [INFO] listening on 0.0.0.0:2013/udp
> 2019-03-15 14:34:46.092 [INFO] admin TCP listener starting on 0.0.0.0:2004
> 2019-03-15 14:34:46.093 [INFO] admin HTTP listener starting on 0.0.0.0:8081

Can the configuration be passed to the docker instance as parameters?

**Comment by DanCech** [comment]
Listening on 0.0.0.0 just means it's listening on all interfaces, so it will be accessible if you publish those ports via docker

https://docs.docker.com/config/containers/container-networking/

**Comment by Dieterbe** [comment]
> How does one edit the configuration file when using the Carbon-Relay-NG Docker Image?

you can include a custom file via a volume mount, or create a new Dockerfile that extends the defaults one and bakes the custom file into a new image
(though, as Dan points out above, you shouldn't even need to do any of this)
