### ISSUE TITLE
Count aggregation

### ISSUE THREAD

**Issue by matthew-hollick** [graphite-ng/carbon-relay-ng#346]
Hi,

a count aggregation would be really handy to have.

Cheers,

Matthew.

**Comment by Dieterbe** [comment]
is this a dup of #344 or do you want actual counts of numbers of points seen? "count aggregation" is ambiguous.

**Comment by DanCech** [comment]
I assumed a "count" option for the aggregator that would just output the number of points received.  In that case if you have control of the values you can do that by sending each one with value `1` and using sum, but it wouldn't be difficult to add.

**Comment by matthew-hollick** [comment]
I don't think that it is a dup of #344 
@DanCech describes my request accurately.
My use case is that the top level of my graphite tree describes the type of metric - be they from collectd, application or statsd and I wish to keep track of the count of metric streams of each type of metric - the cardinality I guess.

**Comment by matthew-hollick** [comment]
I forgot to note that I have a workaround in place in that I have defined multiple outputs with prefix filtering. I then fish out the count of metrics sent from the carbon-relay-ng internal metrics.
(I really thought that i had already posted this but it's been a bust day :-/)

**Comment by Dieterbe** [comment]
> I forgot to note that I have a workaround in place in that I have defined multiple outputs with prefix filtering. I then fish out the count of metrics sent from the carbon-relay-ng internal metrics.

wow. quite the hack but also clever :)

a count aggregator sounds useful, but at least on grafanalabs side, this is not a priority. are you interested in contributing?

**Comment by Dieterbe** [comment]
Hi @matthew-hollick , this is implemented now!
