### ISSUE TITLE
kafkamdm protobuf support

### ISSUE THREAD

**Issue by mevzosvlad** [graphite-ng/carbon-relay-ng#359]
Hello ,
First of all it is a great project and we currently do use it as part of our production flow. 

We are looking to implement kafka as middleware to store the metrics. 
i read this : https://github.com/graphite-ng/carbon-relay-ng/issues/281 so i understand that you do use messagepack for data serialisation.  
I would like to read metrics from kafka using gocarbon(https://github.com/lomik/go-carbon) but it does support either protobuf  or plaintext. 

Do you have any plans to implement protobuf support ? 
May be you do know any projects which provide a good way of reading it from kafka in messagepack and sending it in pickle format for example ? 
Do you have any ideas/implementaion of how to use kafkamdm route in metrics infrastructure stack? 
Thanks in advance, Regards Vlad

**Comment by Dieterbe** [comment]
> Do you have any plans to implement protobuf support ?
not currently
> May be you do know any projects which provide a good way of reading it from kafka in messagepack and sending it in pickle format for example ?
> Do you have any ideas/implementaion of how to use kafkamdm route in metrics infrastructure stack?

our messagepack format is primarily used in the GrafanaLabs stack (for the metrictank datastore and our tsdb-gw service which writes to kafka). I'm not aware of something like what you're describing.
perhaps one could add a kafka input to carbon-relay-ng. but that starts to get ugly. best would be to add support for the protobuf format i suppose, though someone would have to contribute it

**Comment by mevzosvlad** [comment]
Thanks for reply, 
Currently, there is already good implementation of protobuf in Golang: https://github.com/golang/protobuf 
Should be not as complicated to implement it in.  If we will decide to use kafka in our flow , we will spend some time to contribute the project
Regards Vlad
