### ISSUE TITLE
cannot "make" the project

### ISSUE THREAD

**Issue by dorroddorrod** [graphite-ng/carbon-relay-ng#366]
When running 
  go get -d github.com/graphite-ng/carbon-relay-ng
  go get github.com/jteeuwen/go-bindata/...
  cd "$GOPATH/src/github.com/graphite-ng/carbon-relay-ng"
  make

 i get the following error : 

      cd ui/web && go-bindata -pkg web admin_http_assets/...
       find . -name '*.go' | grep -v '^\.\/vendor' | xargs gofmt -w -s
       CGO_ENABLED=0 go build -ldflags "-X main.Version=0.11.0-39-g742bbbd" ./cmd/carbon-relay-ng
       # github.com/graphite-ng/carbon-relay-ng/route
       route/grafananet.go:260:10: undefined: strings.Builder
       make: *** [build] Error 2

Please advice

**Comment by Dieterbe** [comment]
you need a go version >= 1.10
https://golang.org/pkg/strings/#Builder
