### ISSUE TITLE
Pickle listener

### ISSUE THREAD

**Issue by dizzythinks** [graphite-ng/carbon-relay-ng#52]
Is there support for listners for plain text and pickle on relay-ng? I currently have things that send in both to an ordinary Carbon relay daemon which listens on both 2003/2004. I can see that I can send to pickle port as well so I presume that there is support for plain/pickle on the single listen address?

**Comment by dizzythinks** [comment]
Apols if this is not the correct place to ask this

**Comment by Dieterbe** [comment]
2004 is the default admin port.  there's no pickle listener currently

**Comment by dizzythinks** [comment]
ta. Just sussed that with testing :)

**Comment by Dieterbe** [comment]
fwiw i would not be opposed to a PR that adds a pickle listener

**Comment by RobinTalkwalker** [comment]
Is this pickle listener has been implemented since then ?
I would like to switch our "python" carbon relay to carbon-relay-ng but our applications are currently using the pickle protocol and it would be a difficult to move all of them to plain text.

**Comment by Dieterbe** [comment]
Nope. Should be relatively easy to add though, there's a bunch of similar (carbon pickling in Golang) code out there in the wild I believe.
