### ISSUE TITLE
configuration for active/passive clusters.?

### ISSUE THREAD

**Issue by toni-moreno** [graphite-ng/carbon-relay-ng#54]
I've been reading configuration rules and I can understand how can't I define a group of 2 graphite-carbon servers  working together in mode active/passive, something like.

* clusterA = serverA_1:2003 (active) , serverA_2:2003 (passive)
* clusterB = serverB_2:2003 (active), serverB_2:2003 (passive)

 where I should send all metrics matching a regex "^metricsA.*"  only to the first server (active) or the second one if primary fails ( passive) .

something like:

* match "^metricsA.*" send to ClusterA
* match "^metricsB.*" send to clusterB

```
addRoute sendAllMatch regex="^metricsA.*"  serverA_1:2003  serverA_2:2003
addRoute sendAllMatch regex="^metricsB.*"  serverB_1:2003  serverB_2:2003
```

I think there is no way to indicate a active/passive  balancing mode , isn't it?

**Comment by Dieterbe** [comment]
correct, this is currently not available.

**Comment by toni-moreno** [comment]
Hi @Dieterbe do you have plans to add this kind of balancing short or medium term ?

**Comment by Dieterbe** [comment]
no
