### ISSUE TITLE
make: Nothing to be done for `all'.

### ISSUE THREAD

**Issue by cjs226** [graphite-ng/carbon-relay-ng#55]
I'm having problems installing on Ubuntu 14.04 with Go v1.2.  Any help is greatly appreciated.

```
# export GOPATH=/tmp/foo
# export PATH=$PATH:$GOPATH/bin
# go get -d github.com/graphite-ng/carbon-relay-ng
# go get github.com/jteeuwen/go-bindata/...
# cd "$GOPATH/src/github.com/graphite-ng/carbon-relay-ng"
# git checkout v0.5
Note: checking out 'v0.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
                                                                                                                                                                                                    [0/4613]
  git checkout -b new_branch_name

HEAD is now at fa7022b... document new releases / versioning approach
# make
make: Nothing to be done for `all'.
```

**Comment by axelpavageau** [comment]
Hi, 

same issue here, on a Debian 7.5 with Go 1.4.1

Cheers

**Comment by Dieterbe** [comment]
sorry i only started paying attention to the makefile after v0.5 i think.
i don't have time to look into this.
but FWIW i've been running from master in prod for a while now. i would just stick to master if i were you.

**Comment by axelpavageau** [comment]
After getting a couple more packages, build worked for me (on master). 
Thanks.

    $ go get  -u github.com/jteeuwen/go-bindata/...
    $ go get github.com/graphite-ng/carbon-relay-ng/telnet
    $ make
    go-bindata admin_http_assets
    go build
    $ ./carbon-relay-ng 
    13:56:06.889925 ▶ ERRO  Cannot use config file '/etc/carbon-relay-ng.ini':
    13:56:06.889963 ▶ ERRO  open /etc/carbon-relay-ng.ini: no such file or directory
    Usage: carbon-relay-ng <path-to-config>
      -cpuprofile="": write cpu profile to file
