### ISSUE TITLE
Any issue putting multiple carbon-relay-ng in a hardware load balancer?

### ISSUE THREAD

**Issue by blysik** [graphite-ng/carbon-relay-ng#56]
I was thinking of standing up 2 carbon-relay-ng instances in a Citrix Netscaler VIP, pointing to 6 carbon daemons. 

Would there be any problem with this configuration?

Currently I'm using the older, regular, carbon-relay.

**Comment by Dieterbe** [comment]
depends on config of the LB and the carbon "daemons" (what kind of daemons?)

**Comment by blysik** [comment]
The config of the VIP would be pretty standard Direct-Server-Return.  And then carbon-relay-ng points to 6 carbon-cache instances via consistent hashing.  I notice consistent hashing isn't available yet, so this type of config would have to wait. 

Basically I'm attempting to mimic the config we currently have in place using carbon-relay and carbon-cache.

**Comment by Dieterbe** [comment]
yes, if the relay would have CH than that would work.
