### ISSUE TITLE
Feature Request for consistent hashing

### ISSUE THREAD

**Issue by Comradin** [graphite-ng/carbon-relay-ng#58]
Hello,

with some regret I read you had to close the consistent hashing bug. I would like to open this one as an enhancement/feature request for this feature, as it is the one last thing that prevents me from using carbon-relay-ng instead of the original relay-agent.

Sadly Im not a good enough developer to fix this issue, instead I tried some of the existing packages for consistent-hashing and fed them the metrics from my graphite cluster (1M+ metrics), but sadly none of them distributed the metrics in such a way as the pyhton/graphite implementation does.

I had a look at:
	"github.com/golang/groupcache/consistenthash"
	"github.com/ngerakines/ketama"
	"github.com/stathat/consistent"

I failed to make it run with this package, due to a missing understanding how to initialise it with my two backends:  "github.com/dgryski/go-ketama".

If you know of more packages, Ill happily feed my metrics into them to check the distribution ;)

Kind regards,
Marcus

**Comment by Comradin** [comment]
Hi,
just tested "github.com/serialx/hashring", like the others, a different distribution as the *original*.

**Comment by Dieterbe** [comment]
ok, thanks for the info. again, i welcome a good implementation (compatible with carbon) of consistent hashing, but i have no interest (or time) to implement it.
