### ISSUE TITLE
not go-gettable

### ISSUE THREAD

**Issue by t15k** [graphite-ng/carbon-relay-ng#62]
Fails to build (go install github.com/graphite-ng/carbon-relay-ng) with messages:

src/github.com/graphite-ng/carbon-relay-ng/admin_http.go:205: undefined: Asset
src/github.com/graphite-ng/carbon-relay-ng/admin_http.go:205: undefined: AssetDir

**Comment by Dieterbe** [comment]
try following the readme: 
https://github.com/graphite-ng/carbon-relay-ng#building

**Comment by t15k** [comment]
Thanks. I assumed go-gettable. Using make works fine.

**Comment by Dieterbe** [comment]
we could probably make it go-gettable by putting the static files generated by go-bindata into git.. would you mind trying this out and PR'ing?

**Comment by t15k** [comment]
Sure. I'll  take a look at that. Reopening the issue.

**Comment by jschlichtholz** [comment]
I added a pull request. It looks like everything is working fine but I'm not really into go so somebody should verify this. @t15k maybe?

**Comment by t15k** [comment]
Thanks for picking this one up. A clean checkout with
 
    go get github.com/graphite-ng/carbon-relay-ng

gives me 

    src/github.com/graphite-ng/carbon-relay-ng/admin_http.go:234: undefined: Asset
    src/github.com/graphite-ng/carbon-relay-ng/admin_http.go:234: undefined: AssetDir

Investigating...

**Comment by jschlichtholz** [comment]
Yes. The PR is not merged yet. You can try it with `go get github.com/jschlichtholz/carbon-relay-ng`

**Comment by t15k** [comment]
Thanks. Looks good. Can successfully do a go get.

**Comment by jschlichtholz** [comment]
Awesome! Thanks. @Dieterbe, is it okay with you, that changes to `admin_http_assets` require the additional effort?

**Comment by Dieterbe** [comment]
fixed via #97 thanks @jschlichtholz
