### ISSUE TITLE
Docker image for carbon-relay-ng

### ISSUE THREAD

**Issue by yasn77** [graphite-ng/carbon-relay-ng#68]
Hi,

I would just let you know that I have created a small (15.46 MB) Docker image for carbon-relay-ng (since I couldn't find one in the registry).

You can find it here:
https://registry.hub.docker.com/u/yasn77/docker-carbon-relay-ng/

Thanks for the great work!

Yasser

**Comment by Dieterbe** [comment]
neat.
BTW did you know you can build docker images with just the compiled golang binary in it?
searching for "minimal docker golang" should bring up some tutorials

**Comment by yasn77** [comment]
Hi,

Yeh... I did think about using a scratch docker base image, thing is I wanted to utilise environment variables and modify the config based on the environment variables. For that I need a minimal shell (using busybox).
