### ISSUE TITLE
Can't build: "undefined: atomic.Value"

### ISSUE THREAD

**Issue by wstiern** [graphite-ng/carbon-relay-ng#73]
Looking for drop-in replacements for carbon-relay and would really like to try this product. Using CentOS 7 with Go installed from golang-1.3.3.

```
[root@server opt]# mkdir carbon-relay-ng && cd carbon-relay-ng
[root@server carbon-relay-ng]# export GOPATH=/opt/carbon-relay-ng
[root@server carbon-relay-ng]# export PATH="$PATH:$GOPATH/bin"
[root@server carbon-relay-ng]# go get -d github.com/graphite-ng/carbon-relay-ng
[root@server carbon-relay-ng]# go get github.com/jteeuwen/go-bindata/...
[root@server carbon-relay-ng]# cd "$GOPATH/src/github.com/graphite-ng/carbon-relay-ng"
[root@server carbon-relay-ng]# pwd
/opt/carbon-relay-ng/src/github.com/graphite-ng/carbon-relay-ng
[root@server carbon-relay-ng-0.6]# make
go-bindata admin_http_assets
go build
# _/root/carbon-relay-ng-0.6
./table.go:20: undefined: atomic.Value
make: *** [build] Error 2
```

**Comment by daks** [comment]
I have the same issue with the following error
    
    # make
    go-bindata admin_http_assets
    go build
    # github.com/graphite-ng/carbon-relay-ng
    /usr/lib/go/include/src/github.com/graphite-ng/carbon-relay-ng/table.go:20: undefined: atomic.Value
    Makefile:6: recipe for target 'build' failed
    make: *** [build] Error 2

**Comment by Dieterbe** [comment]
this feature was introduced in go 1.4
https://golang.org/doc/go1.4

**Comment by wstiern** [comment]
Thanks, I'm completely inexperienced with Go and appreciate the help. :)

**Comment by daks** [comment]
As another guy completely inexperienced with Go, I ask: could the documentation indicate the minimal Go version needed?

**Comment by olivierHa** [comment]
+1

**Comment by Dieterbe** [comment]
Just fixed it from my phone in a taxi :p
