### ISSUE TITLE
Daemon doesn't listen for UDP datagrams on listen_addr

### ISSUE THREAD

**Issue by herver** [graphite-ng/carbon-relay-ng#78]
Hi, 

I want to replace carbon-relay with this Go implementation as it has all the features I have and many more, but the only thing preventing me to do so, is that (correct me if I'm wrong), carbon-relay-ng wouldn't listen for UDP traffic.

https://github.com/graphite-ng/carbon-relay-ng/blob/master/carbon-relay-ng.go#L235

This is a bummer for me as I do send all the traffic via UDP to the carbon-relay, is this something that could be implemented easily ?

Thanks for the great work !

**Comment by Dieterbe** [comment]
shouldn't be too hard

**Comment by dforste** [comment]
+1

**Comment by hanej** [comment]
+1

**Comment by Dieterbe** [comment]
is anyone going to implement it? because i'm not.

**Comment by hanej** [comment]
I wouldn't mind contributing if this were written in Python but I'm afraid I don't know Go enough to make a meaningful contribution.

**Comment by Dieterbe** [comment]
or maybe y'all should just use tcp instead of udp. is more reliable ;)

**Comment by hanej** [comment]
That's the beauty of udp, it's fire and forget.  The application sending the metrics doesn't have a thread tied up waiting for a tcp response.  When your application is customer facing doing thousands of transactions per second, this is very important.

**Comment by jschlichtholz** [comment]
@Dieterbe This can be closed, I think.

**Comment by Dieterbe** [comment]
yep. thanks @jschlichtholz 
have fun playing with the newly merged UDP support everyone :)
