### ISSUE TITLE
fails to build for me

### ISSUE THREAD

**Issue by blysik** [graphite-ng/carbon-relay-ng#84]
```
# make
go-bindata admin_http_assets
go build
# github.com/graphite-ng/carbon-relay-ng/_third_party/github.com/kisielk/og-rek
_third_party/github.com/kisielk/og-rek/ogórek.go:20: opMark redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:20
_third_party/github.com/kisielk/og-rek/ogórek.go:21: opStop redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:21
_third_party/github.com/kisielk/og-rek/ogórek.go:22: opPop redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:22
_third_party/github.com/kisielk/og-rek/ogórek.go:23: opPopMark redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:23
_third_party/github.com/kisielk/og-rek/ogórek.go:24: opDup redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:24
_third_party/github.com/kisielk/og-rek/ogórek.go:25: opFloat redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:25
_third_party/github.com/kisielk/og-rek/ogórek.go:26: opInt redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:26
_third_party/github.com/kisielk/og-rek/ogórek.go:27: opBinint redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:27
_third_party/github.com/kisielk/og-rek/ogórek.go:28: opBinint1 redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:28
_third_party/github.com/kisielk/og-rek/ogórek.go:29: opLong redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:29
_third_party/github.com/kisielk/og-rek/ogórek.go:29: too many errors
# github.com/graphite-ng/carbon-relay-ng/_third_party/github.com/elazarl/go-bindata-assetfs
_third_party/github.com/elazarl/go-bindata-assetfs/assetfs.go:78: AssetFile.Size is ambiguous
_third_party/github.com/elazarl/go-bindata-assetfs/assetfs.go:78: cannot use f (type *AssetFile) as type os.FileInfo in return argument:
	*AssetFile does not implement os.FileInfo (missing Size method)
_third_party/github.com/elazarl/go-bindata-assetfs/assetfs.go:118: AssetDirectory.Size is ambiguous
_third_party/github.com/elazarl/go-bindata-assetfs/assetfs.go:118: cannot use f (type *AssetDirectory) as type os.FileInfo in return argument:
	*AssetDirectory does not implement os.FileInfo (missing Size method)
make: *** [build] Error 2
```

**Comment by gmlwall** [comment]
i am also receiving a build error;

go-bindata admin_http_assets
go build
# github.com/graphite-ng/carbon-relay-ng/_third_party/github.com/kisielk/og-rek
_third_party/github.com/kisielk/og-rek/ogórek.go:20: opMark redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:20
_third_party/github.com/kisielk/og-rek/ogórek.go:21: opStop redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:21
_third_party/github.com/kisielk/og-rek/ogórek.go:22: opPop redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:22
_third_party/github.com/kisielk/og-rek/ogórek.go:23: opPopMark redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:23
_third_party/github.com/kisielk/og-rek/ogórek.go:24: opDup redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:24
_third_party/github.com/kisielk/og-rek/ogórek.go:25: opFloat redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:25
_third_party/github.com/kisielk/og-rek/ogórek.go:26: opInt redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:26
_third_party/github.com/kisielk/og-rek/ogórek.go:27: opBinint redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:27
_third_party/github.com/kisielk/og-rek/ogórek.go:28: opBinint1 redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:28
_third_party/github.com/kisielk/og-rek/ogórek.go:29: opLong redeclared in this block
	previous declaration at _third_party/github.com/kisielk/og-rek/ogórek.go:29
_third_party/github.com/kisielk/og-rek/ogórek.go:29: too many errors
make: *** [build] Error 2

**Comment by blysik** [comment]
I was able to resolve this by removing the unicode version of the files in the directory.  It appears that project is in the middle of renaming things out of the polish word.

**Comment by blysik** [comment]
Oh, I had to change all the package declaration names, and how it was called from pickle.go also.

**Comment by gmlwall** [comment]
ah nice, i git checkout'ed to earlier version and built it to test :)

**Comment by tbielawa** [comment]
"Me too"

I was able to get the last official release to build, but HEAD is totally bonkers right now :(

I guess that's the price we pay for living on the bleeding edge :-)

**Comment by tbielawa** [comment]
Does anyone know if services like Travis have golang support (yet)? That'd be a pretty sweet enhancement for this project, automatic build verification.

**Comment by rtkrruvinskiy** [comment]
Hmm, so _third_party/github.com/kisielk/og-rek/ogórek.go came in with my commit to add consistent routing tests, and it was added because I ran `party -t`. I was actually confused as to why that file was added, but I figured it pulled in a newer revision of the dependency.

It built perfectly fine for me on a Ubuntu 12.04 VM x86_64 VM with go1.4.2. I also just tried on OS X 10.10.4 with go1.4.2, and it built fine there, too. On what platforms and with what compiler version is it failing to build?

**Comment by tbielawa** [comment]
I made a quick [showterm](https://showterm.io/) (terminal capture) to demonstrate the issue on my host

* http://showterm.io/f3b179c53c08e47422e71

for reference:

```
[/tmp/tmp.eC2IQWxwPy] 12:01:43 
$ cat /etc/redhat-release 
Fedora release 22 (Twenty Two)
[/tmp/tmp.eC2IQWxwPy] 12:02:45 
$ rpm -q golang
golang-1.4.2-2.fc22.x86_64
```

**Comment by rtkrruvinskiy** [comment]
Out of curiosity, what's your locale? `echo $LANG`

**Comment by Dieterbe** [comment]
when i git pull, i get this
```
dieter@dieter-m6800 carbon-relay-ng git pull origin
remote: Counting objects: 38, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 38 (delta 6), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (38/38), done.
From github.com:rcrowley/carbon-relay-ng
   a488123..3219a94  master     -> origin/master
Updating a488123..3219a94
Fast-forward
 README.md                                                       |  10 +-
 _third_party/github.com/bmizerany/assert/README.md              |  45 +++++++
 _third_party/github.com/bmizerany/assert/assert.go              |  77 ++++++++++++
 _third_party/github.com/bmizerany/assert/assert_test.go         |  15 +++
 "_third_party/github.com/kisielk/og-rek/ogo\314\201rek.go"      | 806 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 "_third_party/github.com/kisielk/og-rek/ogo\314\201rek_test.go" | 174 ++++++++++++++++++++++++++
 _third_party/github.com/kr/pretty/License                       |  21 ++++
 _third_party/github.com/kr/pretty/Readme                        |   9 ++
 _third_party/github.com/kr/pretty/diff.go                       | 158 +++++++++++++++++++++++
 _third_party/github.com/kr/pretty/diff_test.go                  |  74 +++++++++++
 _third_party/github.com/kr/pretty/example_test.go               |  20 +++
 _third_party/github.com/kr/pretty/formatter.go                  | 337 +++++++++++++++++++++++++++++++++++++++++++++++++
 _third_party/github.com/kr/pretty/formatter_test.go             | 261 ++++++++++++++++++++++++++++++++++++++
 _third_party/github.com/kr/pretty/pretty.go                     |  98 +++++++++++++++
....
```

that's a few weird filenames in there

**Comment by tbielawa** [comment]
```
[~] 12:17:42 
$ echo $LANG; echo $SHELL
en_US.utf8
/bin/zsh
```
