### ISSUE TITLE
provide pre-built binaries for common platforms

### ISSUE THREAD

**Issue by blysik** [graphite-ng/carbon-relay-ng#85]
To assist people in getting started, maybe supply prebuilt binaries for some platforms.

linux-amd64 comes to mind first.

**Comment by Dieterbe** [comment]
i don't have time for this but i welcome and support anyone setting something up for this.
perhaps circleci.com ? i see it's free for OSS and supposedly it lets you download all build artifacts.

**Comment by Dieterbe** [comment]
we have this all set up now @blysik 
see https://github.com/graphite-ng/carbon-relay-ng/releases/tag/v0.8 for details
