### ISSUE TITLE
package angular and bootstrap with carbon-relay-ng

### ISSUE THREAD

**Issue by blysik** [graphite-ng/carbon-relay-ng#87]
I'm unable to load the http page because of these errors:

[blocked] The page at https://xxx.xxx.xxx/ was not allowed to run insecure content from http://code.angularjs.org/1.2.10/angular.min.js.

(Because I'm putting carbon-relay-ng behind a proxy which serves via https.)

**Comment by Dieterbe** [comment]
yeah we should probably do this

**Comment by jschlichtholz** [comment]
@blysik could you recheck if this is still an issue? Could be resolved with #88.

**Comment by efficks** [comment]
I have the same problem when using carbon-relay-ng in a closed network. I will do a PR

**Comment by Dieterbe** [comment]
this should be fixed now
