### ISSUE TITLE
Rewrite for OpenTSDB destination

### ISSUE THREAD

**Issue by dlmarion** [graphite-ng/carbon-relay-ng#92]
I was wondering if carbon-relay-ng has the ability to rewrite the output metric to the OpenTSDB format:

`put <metric> <timestamp> <value> <tagk1=tagv1[ tagk2=tagv2 ...tagkN=tagvN]>`

I think what I really need to do is swap the value and timestamp from the Graphite output format as I don't have any tags.

**Comment by Dieterbe** [comment]
it does not

**Comment by dlmarion** [comment]
Thanks for the quick reply.
