### ISSUE TITLE
Ability to send only aggregated metrics

### ISSUE THREAD

**Issue by wf1nder** [graphite-ng/carbon-relay-ng#96]
Now relay sends both original and aggregated metrics into routing. It would be cool if there was option in config that disables output the original data, leaving only aggregatad. Can you implement it?
Thanks.

**Comment by guillaumeautran** [comment]
I've came up the similar issue where the input data comes in at an interval of 10seconds but the aggregation is done over a longer period of time (30mins). My solution to the problem of discarding the original input was simply do define my routing such that only the aggregated data is being picked-up and sent over the route. The original data just "falls off" the end of the routing chain...

**Comment by Dieterbe** [comment]
yeah that should do it. and that was also the reason for #198
